export const ACTION_TYPE = {

	// ORDERS
	SELECT_ORDER: 'SELECT_OTDER',
	DESELECT_ORDER: 'DESELECT_ORDER',
	REMOVE_ORDERS: 'REMOVE_ORDER',
	SEND_ORDERS: 'SEND_ORDERS',
	ADD_ORDERS: 'ADD_ORDER',
	// suppose remove its
	SIGN_IN: 'SIGN_IN',
	LOGOUT: 'LOGOUT',
	LOGIN: 'LOGIN',
	// ORDER ITEMS
	ADD_TO_SELECTED_ITEMS: 'ADD_TO_SELECTED_ITEMS',
	REMOVE_FROM_SELECTED_ITEMS: 'REMOVE_FROM_SELECTED_ITEMS',
	ADD_ITEMS: 'ADD_ITEMS',
	REMOVE_ITEMS: 'REMOVE_ITEMS',
	// STAGES OF ORDERING
	GO_NEXT: 'GO_NEXT',
	// ENDPOINTS
	ADD_ENDPOINTS: 'GET_ENDPOINTS',
	// VENDORS
	ADD_VENDORS: 'GET_VENDORS'
};
